import { afterAll, describe, it } from "vitest";

/**
 * Runs Better Auth's own official adapter conformance suite
 * (`@better-auth/test-utils/adapter`) against a *real* Postgres database via
 * the real `@prisma/orm-postgres` runtime — no mocks, no fakes anywhere in
 * this file. This is what caught the `updateCount`/`deleteCount` bug: the
 * real package spells them `updateAndCount`/`deleteAndCount`, which Prisma's
 * own docs get wrong for this package version.
 *
 * Every suite the package exports runs, with nothing disabled: the fixture
 * derives both the DDL and the Prisma contract from `getAuthTables(options)`
 * and re-derives them whenever the resolved schema changes, so the ~30 tests
 * that introduce a mid-run schema change (an extra plugin model, an added
 * field, a renamed column or model, serial vs. string ids) are exercised for
 * real instead of being skipped.
 *
 * Opt-in: set `LIVE_PG_URL` to a real Postgres connection string to run it.
 * Skipped (not failed) otherwise, so `pnpm test` stays green without one.
 *
 * Use a *local* database. The suite issues on the order of ten thousand
 * sequential round trips: ~80s against localhost, but several hours against a
 * hosted database across a ~270ms round trip — which looks exactly like a
 * hang. That is a property of the suite, not of the adapter.
 */
const DIRECT_URL = process.env["LIVE_PG_URL"];

describe.skipIf(!DIRECT_URL)(
	"OFFICIAL @better-auth/test-utils adapter conformance suite, against LIVE Postgres",
	() => {
		it("placeholder — the real suite is registered at module scope below when LIVE_PG_URL is set", () => {
			// Intentionally empty. `@better-auth/test-utils`'s `execute()` needs
			// to call vitest's own `describe(...)` at module scope (not nested
			// inside a test), so the real suite is registered further down,
			// guarded by the same `DIRECT_URL` check. This block exists only so
			// vitest has something to report when the live suite is skipped.
		});
	},
);

if (DIRECT_URL) {
	await runLiveSuite(DIRECT_URL);
}

async function runLiveSuite(url: string) {
	// Prisma 8 rc's `field.dateTime()` codec requires the TC39 Temporal
	// global, which no current Node.js version ships natively. Any real app
	// on this rc needs a polyfill; the adapter can't work around it.
	const { Temporal } = await import("@js-temporal/polyfill");
	(globalThis as any).Temporal ??= Temporal;

	const { Client } = await import("pg");
	const { defineContract } = await import("@prisma/orm-postgres/contract-builder");
	const { default: postgres } = await import("@prisma/orm-postgres/runtime");
	const {
		testAdapter,
		normalTestSuite,
		transactionsTestSuite,
		caseInsensitiveTestSuite,
		numberIdTestSuite,
		uuidTestSuite,
		joinsTestSuite,
		authFlowTestSuite,
	} = await import("@better-auth/test-utils/adapter");
	const { prisma8Adapter } = await import("./prisma8-adapter");
	const { getAuthTables } = await import("better-auth/db");

	/**
	 * Which primary-key strategy the *currently applied* Better Auth options
	 * ask for. `numberIdTestSuite` sets `generateId: "serial"`, which means the
	 * database mints the id and Better Auth omits it from the insert payload
	 * entirely — a fixed `id TEXT PRIMARY KEY` script therefore fails every
	 * write in that suite with a not-null violation, which is a bug in the
	 * fixture, not in the adapter.
	 *
	 * `generateId: "uuid"` needs its own mode for a related reason: the
	 * adapter now declares `supportsUUIDs: true` on PostgreSQL (matching
	 * Kysely, Drizzle, and Prisma classic's own adapters), so
	 * `uuidTestSuite` omits the id from every insert too — expecting
	 * `field.id.uuidv7String()` (see `buildContract` below) to generate it
	 * client-side, in the ORM runtime, before the insert reaches the
	 * database. A contract with no id preset at all fails the same way
	 * `serial` mode did before it got its own `IdMode`.
	 */
	type IdMode = "text" | "serial" | "uuid";

	const idModeFor = (options: any): IdMode => {
		const generateId = options?.advanced?.database?.generateId;
		if (generateId === "serial") return "serial";
		if (generateId === "uuid") return "uuid";
		return "text";
	};

	/**
	 * `GENERATED BY DEFAULT` (not `ALWAYS`): the suite still supplies explicit
	 * ids for some `forceAllowId` cases, and `BY DEFAULT` accepts both a
	 * supplied value and an omitted one.
	 *
	 * `uuid` mode needs no SQL-level default at all: `field.id.uuidv7String()`
	 * (see `buildContract` below) generates the id *client-side*, in the ORM
	 * runtime, before the insert — the same mechanism `createdAt`'s
	 * `instantNow` generator uses. A plain `TEXT` column, matching how
	 * Better Auth types every foreign key, is enough.
	 */
	const idColumnSql = (mode: IdMode) => {
		if (mode === "serial") return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
		return "TEXT PRIMARY KEY";
	};
	const fkColumnSql = (mode: IdMode) => (mode === "serial" ? "INTEGER" : "TEXT");

	/** PascalCase, matching the adapter's own `toContractModelName`. */
	const pascal = (name: string) =>
		name.length === 0 ? name : name[0]!.toUpperCase() + name.slice(1);

	/**
	 * Better Auth addresses a column by `field.fieldName ?? <schema key>`, and
	 * so does this adapter (everything is put through `getFieldName` before it
	 * reaches the ORM field proxy). Keying the contract by the column name —
	 * rather than by the schema key with a `.sql({ column })` mapping — is what
	 * makes the "modified field name" tests line up.
	 */
	const columnOf = (key: string, field: any): string => field.fieldName ?? key;

	const sqlTypeFor = (field: any): string => {
		// `Array<LiteralString>` — a string-literal union, stored as text.
		if (Array.isArray(field.type)) return "TEXT";
		switch (field.type) {
			case "string":
				return "TEXT";
			case "number":
				return field.bigint ? "BIGINT" : "INTEGER";
			case "boolean":
				return "BOOLEAN";
			case "date":
				return "TIMESTAMPTZ";
			case "json":
				return "JSONB";
			case "string[]":
				return "TEXT[]";
			case "number[]":
				return "INTEGER[]";
			default:
				throw new Error(`Unsupported Better Auth field type: ${String(field.type)}`);
		}
	};

	/**
	 * Better Auth's own migrator (`get-migration.mjs`) reads this as
	 * `field.references.onDelete || "cascade"`, and both of this package's
	 * schema generators default the same way — so the fixture has to as well.
	 * Leaving an unspecified reference at Postgres's `NO ACTION` default makes
	 * the harness's row cleanup fail on the FK (it swallows the error), and
	 * the leftover rows then break the *next* test's counts.
	 */
	const onDeleteSql = (action: string | undefined) => {
		switch (action ?? "cascade") {
			case "cascade":
				return " ON DELETE CASCADE";
			case "set null":
				return " ON DELETE SET NULL";
			case "restrict":
				return " ON DELETE RESTRICT";
			case "no action":
				return " ON DELETE NO ACTION";
			default:
				return "";
		}
	};

	/**
	 * The attribute a `references` clause points at, or `null` when it points
	 * at the implicit `id` column (which no `table.fields` entry describes).
	 */
	const referencedAttribute = (
		tables: Record<string, any>,
		references: any,
	): any | null => {
		const target = tables[references.model];
		if (!target || references.field === "id") return null;
		return target.fields[references.field] ?? null;
	};

	/**
	 * The whole DDL script for one resolved Better Auth schema.
	 *
	 * Derived from `getAuthTables(options)` rather than hard-coded, because
	 * 29 of the suite's tests introduce a schema change mid-run (an extra
	 * plugin model, an additional field, a renamed column or model) and then
	 * ask the harness to migrate to it. A fixed four-model script cannot
	 * answer that, and skipping those tests is not free either: they are the
	 * only coverage for joins, `additionalFields`, and field/model renaming,
	 * and skipping one also skips the `modifyBetterAuthOptions` call inside it
	 * that resets options for every test that follows.
	 *
	 * Foreign keys are added in a second pass so table creation order never
	 * matters.
	 */
	const ddlFor = (tables: Record<string, any>, mode: IdMode): string => {
		const referencedColumnSql = (references: any, idMode: IdMode): string => {
			const attribute = referencedAttribute(tables, references);
			return attribute ? sqlTypeFor(attribute) : fkColumnSql(idMode);
		};

		const drops: string[] = [];
		const creates: string[] = [];
		const alters: string[] = [];

		for (const table of Object.values(tables)) {
			drops.push(`DROP TABLE IF EXISTS "${table.modelName}" CASCADE;`);

			const columns: string[] = [`  "id" ${idColumnSql(mode)}`];
			for (const [key, field] of Object.entries<any>(table.fields)) {
				const column = columnOf(key, field);
				// A foreign key column has to match the column it points at —
				// which is usually the id (and so follows the id mode), but not
				// always: `findOne - should join a model with modified field
				// name` points a reference at a renamed `email` column, and
				// giving that an integer type makes Postgres reject the
				// constraint outright with "key columns are of incompatible
				// types".
				const type = field.references
					? referencedColumnSql(field.references, mode)
					: sqlTypeFor(field);
				const nullability = field.required ? " NOT NULL" : "";
				const unique = field.unique ? " UNIQUE" : "";
				columns.push(`  "${column}" ${type}${nullability}${unique}`);

				if (field.references) {
					const target = tables[field.references.model];
					const targetTable = target?.modelName ?? field.references.model;
					const targetColumn =
						field.references.field === "id" || !target
							? field.references.field
							: columnOf(
									field.references.field,
									target.fields[field.references.field] ?? {},
								);
					alters.push(
						`ALTER TABLE "${table.modelName}" ADD FOREIGN KEY ("${column}") ` +
							`REFERENCES "${targetTable}"("${targetColumn}")${onDeleteSql(field.references.onDelete)};`,
					);
				}
				if (field.index) {
					alters.push(
						`CREATE INDEX ON "${table.modelName}" ("${column}");`,
					);
				}
			}

			creates.push(`CREATE TABLE "${table.modelName}" (\n${columns.join(",\n")}\n);`);

			for (const index of table.indexes ?? []) {
				const columnList = (index.fields as string[])
					.map((f) => `"${columnOf(f, table.fields[f] ?? {})}"`)
					.join(", ");
				alters.push(
					index.unique
						? `ALTER TABLE "${table.modelName}" ADD UNIQUE (${columnList});`
						: `CREATE INDEX ON "${table.modelName}" (${columnList});`,
				);
			}
		}

		// Drops run in reverse declaration order so a dependent table goes
		// before the one it points at; `CASCADE` covers the rest.
		return [...drops.reverse(), ...creates, ...alters].join("\n");
	};

	/** The matching Prisma Next contract for the same resolved schema. */
	const buildContract = (tables: Record<string, any>, mode: IdMode) =>
		defineContract({}, ({ field, model }) => {
			const idField = () => {
				if (mode === "serial") return field.int().id();
				if (mode === "uuid") return field.id.uuidv7String();
				return field.text().id();
			};
			const fkField = () => (mode === "serial" ? field.int() : field.text());

			const scalarFor = (attribute: any): any => {
				if (attribute.references) {
					// Same rule as the DDL: mirror the referenced column's type,
					// which is the id type only when the reference targets `id`.
					const target = referencedAttribute(tables, attribute.references);
					return target ? scalarFor(target) : fkField();
				}
				if (Array.isArray(attribute.type)) return field.text();
				switch (attribute.type) {
					case "string":
						return field.text();
					case "number":
						return attribute.bigint ? field.bigint() : field.int();
					case "boolean":
						return field.boolean();
					case "date":
						return field.dateTime();
					case "json":
						return field.json();
					case "string[]":
						return field.text().many();
					case "number[]":
						return field.int().many();
					default:
						throw new Error(
							`Unsupported Better Auth field type: ${String(attribute.type)}`,
						);
				}
			};

			const models: Record<string, any> = {};
			for (const table of Object.values<any>(tables)) {
				const fields: Record<string, any> = { id: idField() };
				for (const [key, attribute] of Object.entries<any>(table.fields)) {
					let builder = scalarFor(attribute);
					if (attribute.unique) builder = builder.unique();
					if (!attribute.required) builder = builder.optional();
					fields[columnOf(key, attribute)] = builder;
				}
				const name = pascal(table.modelName);
				models[name] = model(name, { fields }).sql({ table: table.modelName });
			}

			// No `rel.*` declarations: Better Auth's factory resolves joins
			// itself with follow-up queries (`handleFallbackJoin`) unless
			// `advanced.database.joins` is on, and this adapter does not
			// implement native joins — so the ORM's own relation graph is
			// never consulted.
			return { models };
		});

	const pgClient = new Client({ connectionString: url });

	/** The connection string with any password replaced, safe to print. */
	const redact = (connectionString: string) => {
		try {
			const parsed = new URL(connectionString);
			if (parsed.password) parsed.password = "***";
			return parsed.toString();
		} catch {
			return "<unparseable connection string>";
		}
	};

	/**
	 * Fail fast, and legibly, when `LIVE_PG_URL` is set but unusable.
	 *
	 * Without this the first real query is what discovers the problem, and the
	 * ORM reports it as "Database error while reading contract marker" under a
	 * wall of driver stack traces — the actual cause ("database ... does not
	 * exist") is buried four `Caused by:` levels down.
	 *
	 * Also measures round-trip latency, because this suite's cost is entirely
	 * per-statement: it issues on the order of ten thousand sequential
	 * statements, so a hosted database an ocean away turns an 80-second run
	 * into a multi-hour one that is indistinguishable from a hang.
	 */
	async function preflight() {
		try {
			await pgClient.connect();
		} catch (error) {
			throw new Error(
				`LIVE_PG_URL is set, but the database could not be reached.\n` +
					`  url:   ${redact(url)}\n` +
					`  cause: ${error instanceof Error ? error.message : String(error)}\n` +
					`  Create the database first, or unset LIVE_PG_URL to skip this suite.`,
				{ cause: error },
			);
		}

		const started = Date.now();
		const probes = 5;
		for (let i = 0; i < probes; i++) await pgClient.query("SELECT 1");
		const perStatement = (Date.now() - started) / probes;

		if (perStatement > 25) {
			const estimateMinutes = Math.round((perStatement * 10_000) / 60_000);
			console.warn(
				`\n[live-suite] ${perStatement.toFixed(0)}ms per round trip to ${redact(url)}.\n` +
					`[live-suite] This suite issues ~10,000 sequential statements, so expect ` +
					`roughly ${estimateMinutes} minutes — it is not hung, just far away.\n` +
					`[live-suite] Point LIVE_PG_URL at a local Postgres to finish in ~80s.\n`,
			);
		}
	}

	await preflight();

	const makeDb = (tables: Record<string, any>, mode: IdMode) =>
		postgres({
			contract: buildContract(tables, mode),
			url,
			// The suite runs thousands of ops; a short default idle timeout
			// otherwise culls the pooled connection mid-run, surfacing as
			// "Postgres driver not connected" well after the run appeared to
			// be progressing normally. Pool *size* is not configurable on this
			// rc — `poolOptions` only accepts the two timeouts — so the only
			// defence against exhausting the server's connection slots is
			// closing each client when the schema moves on (see `syncSchema`).
			poolOptions: {
				idleTimeoutMillis: 300_000,
				connectionTimeoutMillis: 30_000,
			},
		});

	let activeDb: ReturnType<typeof makeDb> | null = null;

	// Rebuilding the client and the tables on every call is wasteful when the
	// schema did not actually change, so the resolved shape is fingerprinted
	// and compared first.
	let activeFingerprint: string | null = null;

	const fingerprintOf = (tables: Record<string, any>, mode: IdMode) =>
		`${mode}:${JSON.stringify(
			Object.values(tables).map((t: any) => [
				t.modelName,
				Object.entries<any>(t.fields).map(([k, f]) => [
					columnOf(k, f),
					String(f.type),
					!!f.required,
					!!f.unique,
					f.references?.model ?? null,
					f.references?.field ?? null,
				]),
				t.indexes ?? [],
			]),
		)}`;

	/**
	 * Point the ORM client at `options`' resolved schema, rebuilding it only
	 * when the shape actually changed.
	 *
	 * Deliberately does **not** touch the database. `runMigrations` is the only
	 * thing allowed to run DDL: the script is a DROP/CREATE, so running it from
	 * anywhere the harness does not expect (this is handed out before *every*
	 * adapter operation) can wipe rows a test has already inserted, which
	 * surfaces later as a foreign-key violation on a row whose parent
	 * "vanished".
	 *
	 * The old client is closed on every swap. Leaking it is not a slow leak:
	 * the suite changes schema dozens of times, and Postgres starts refusing
	 * connections ("sorry, too many clients already") partway through, which
	 * the ORM surfaces as the much less obvious "Database error while reading
	 * contract marker".
	 */
	const syncClient = async (tables: Record<string, any>, mode: IdMode) => {
		const fingerprint = fingerprintOf(tables, mode);
		if (fingerprint === activeFingerprint && activeDb) return;
		const previous = activeDb;
		activeDb = makeDb(tables, mode);
		activeFingerprint = fingerprint;
		if (previous) await previous.runtime().close();
	};

	const { execute } = await testAdapter({
		adapter: async (options: any) => {
			await syncClient(getAuthTables(options), idModeFor(options));
			return (resolved: any) =>
				prisma8Adapter(activeDb as any, {
					provider: "postgresql",
					transaction: true,
				})(resolved) as any;
		},
		runMigrations: async (options: any) => {
			const tables = getAuthTables(options);
			const mode = idModeFor(options);
			try {
				await pgClient.connect();
			} catch {
				// already connected — the harness migrates once per test group
			}
			await pgClient.query(ddlFor(tables, mode));
			await syncClient(tables, mode);
		},
		// Every suite the package exports, with nothing disabled.
		tests: [
			normalTestSuite(),
			transactionsTestSuite(),
			caseInsensitiveTestSuite(),
			numberIdTestSuite(),
			uuidTestSuite(),
			joinsTestSuite(),
			authFlowTestSuite(),
		],
	});

	afterAll(async () => {
		await pgClient.end();
		await activeDb?.runtime().close();
	});

	execute();
}
